#!/usr/bin/env php
<?php

declare(strict_types=1);

use GiacomoMasseroni\PHPCleanArchitecture\Application;

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

exit((new Application())->run($_SERVER['argv']));
